class User:
    def __init__(self, 
                 first_name:str="", 
                 last_name:str="", 
                 day_last_name:str="", 
                 civility:str="", 
                 nationality:str="", 
                 birthday:str="", 
                 birthday_location:str="", 
                 address:str="", 
                 city:str="", 
                 zipcode:str="", 
                 email:str="", 
                 phone:str="", 
                 job:str="", 
                 relationship:str="", 
                 nb_kids:str="", 
                 member_function:str="", 
                 start_subscription:str="", 
                 end_subscription:str="", 
                 activity:str="", 
                 member_id:str="",
                 ID:int=0):
        
        self.ID = ID
        self.first_name = first_name
        self.last_name = last_name
        self.day_last_name = day_last_name
        self.civility = civility
        self.nationality = nationality
        self.birthday = birthday
        self.birthday_location = birthday_location
        self.start_subscription = start_subscription
        self.end_subscription = end_subscription
        self.address = address
        self.city = city
        self.zipcode = zipcode
        self.email = email
        self.phone = phone
        self.job = job
        self.relationship = relationship
        self.nb_kids = nb_kids
        self.member_id = member_id
        self.member_function = member_function
        self.activity = activity

    def __list__(self) -> list:
        """
        Returns a list of all attribute values of the User instance.

        The list is generated by iterating over the instance's attributes and
        collecting their values.

        Parameters:
        None

        Returns:
        list: A list containing all attribute values of the User instance.
        """
        return [value for key, value in self.__dict__.items()]

    def __attr__(self) -> list:
        """
        Returns a list of all attribute names of the User class.

        This method is used to retrieve a list of all attribute names defined in the User class.
        The attribute names are obtained by iterating over the dictionary of the class instance
        (User().__dict__) and collecting the keys.

        Parameters:
        None

        Returns:
        list: A list containing all attribute names of the User class.
        """
        return list(User().__dict__.keys())
